FROM ubuntu:12.04
RUN sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
RUN apt-get update && apt-get install -y ruby1.8 rubygems1.8 ruby1.8-dev build-essential
RUN update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby1.8 1 \
 && update-alternatives --install /usr/bin/gem gem /usr/bin/gem1.8 1
RUN gem install -v 1.3.7 rubygems-update --no-rdoc --no-ri && update_rubygems
RUN gem install rake -v 0.8.7 --no-rdoc --no-ri
RUN gem install rack -v 1.1.6 --no-rdoc --no-ri
RUN gem install json -v 1.8.1 --no-rdoc --no-ri
RUN gem install mongrel -v 1.1.5 --no-rdoc --no-ri
RUN gem install rails -v 2.3.18 --no-rdoc --no-ri
